name: Build

on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/cache@v2.1.6
      with:
        path: /home/runner/go
        key: v1-go-mod-${{ hashFiles('go.sum') }}
        restore-keys: v1-go-mod-
    - uses: winchci/actions-golang@v1
